version: "3"
services:
  postgres:
    image: postgres:10.4
    container_name: postgres-security
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
  app:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      NODE_ENV: development
      PORT: 3333
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/desafio'
    ports:
      - "3333:3333"
    command: npm run dev:server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/migrations

